### ISSUE TITLE
Bot stopped due to risk of ban

### ISSUE THREAD

**Issue by Pedram987** [Freddywhest/TonStationBot#7]
![Screenshot 2024-11-02 180740](https://github.com/user-attachments/assets/de924171-227d-4dcb-90fe-27e9ae600737)

**Comment by vstri** [comment]
now again
![image](https://github.com/user-attachments/assets/e524037c-2a97-4c68-a86a-18c3b977e4d5)

**Comment by Color-maN** [comment]
Классная функция. Дружно ждем обновлений)

**Comment by PTPL-LKO** [comment]
again TonStation make changes

```
[2024-11-06 12:55:07] | ERROR | [tonstation] | saif | Bot stopped | Detected some changes with TON Station which may cause ban. Contact the developer and report this issue. 
GitHub: https://github.com/FreddyWhest 
Telegram: @roddyfred
```
